0  REM <CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H>ABOUT THE PDSOF SERVICE<CTRL-M><CTRL-M>PROGRAM BY GREG TANG<CTRL-M><CTRL-M><CTRL-M>
10  GOTO 70
20  HTAB (21 - LEN(H$)/2): PRINT H$;: RETURN 
30 R = 0:L = 1
40  READ A$: IF A$ = "*"  THEN MX = R: RETURN 
50 B$ =  LEFT$(A$,1): IF B$ < >"*"  THEN A$(R,L) = A$:L = L +1: GOTO 40
60 R = R +1:L = 1:A$(R,0) =  RIGHT$(A$, LEN(A$) -1): GOTO 40
70 D$ =  CHR$(13) + CHR$(4): DIM A$(20,18): HOME : TEXT : INVERSE 
80  VTAB 23: HTAB 2: PRINT " ";: HTAB 39: PRINT " ": HTAB 2: PRINT "                                      ";: POKE 34,0
90  INVERSE : FOR V = 23 TO 2  STEP  -1: VTAB V: HTAB 1: PRINT " ";: HTAB 40: PRINT " ";: NEXT 
100  VTAB 3: HTAB 4: PRINT  TAB( 38);: VTAB 2: HTAB 1: PRINT  TAB( 41);: VTAB 1: HTAB 4: PRINT  TAB( 38): VTAB 2:H$ = "ABOUT THE PDSOF SERVICE": GOSUB 20: NORMAL : VTAB 12:H$ = " ONE MOMENT PLEASE ....": GOSUB 20: POKE  -16368,0: POKE 34,5: GOSUB 40: VTAB 13: HTAB 2: PRINT  TAB( 39);
110  POKE 32,0: POKE 33,40: POKE 34,0: POKE 35,24
120  FOR I = 1 TO MX: INVERSE : VTAB 2: HTAB 3: PRINT  TAB( 39);:H$ = A$(I,0): GOSUB 20: NORMAL : FOR J = 1 TO 18: VTAB J +4: HTAB 3: PRINT A$(I,J); TAB( 40);: NEXT J: IF I = MX  THEN 140
130  GOSUB 180: NEXT I
140  POKE  -16368,0: VTAB 18: HTAB 18: PRINT "- - -": VTAB 20: HTAB 8: PRINT "PRESS <ESC> TO RETURN TO": HTAB 6: PRINT "THE OPENING MENU OR PRESS ANY": HTAB 4: PRINT "OTHER KEY TO READ THIS FILE AGAIN";
150  GET A$: IF A$ < > CHR$(27)  THEN 120
160  TEXT : HOME : VTAB 10: HTAB 10: PRINT "LOADING OPENING MENU": VTAB 12: HTAB 13: PRINT "PLEASE WAIT ..."
170  PRINT D$"RUN OPENING MENU"
180  INVERSE : VTAB 24: HTAB 3: PRINT "<ESC> TO EXIT, <ANY KEY> TO CONTINUE";: POKE  -16368,0
190 A =  PEEK( -16384): IF A < = 127  THEN 190
200 A$ =  CHR$(A -128): IF A$ =  CHR$(27)  THEN  NORMAL : GOTO 160
210  VTAB 24: HTAB 2: PRINT "                                      ";: NORMAL : RETURN 
9000  REM <CTRL-J><CTRL-J>DATA BANK<CTRL-J><CTRL-J>
9050  DATA "*THE PDSOF SERVICE","WE AND YOUR LIBRARY ARE PLEASED TO","PRESENT THESE PROGRAMS TO YOU."," ","PUBLIC DOMAIN SOFTWARE ON FILE","(PDSOF) IS A PART OF THE FACTS ON","FILE PUBLISHING HOUSE.  WE HAVE BEEN"
9100  DATA "SERVING YOU AND THE LIBRARY","COMMUNITY FOR SEVERAL DECADES WITH","QUALITY REFERENCE AND INFORMATION","MATERIALS.","*THE PDSOF SERVICE (CONT)","THE AWARD-WINNING PROGRAMS WERE","SELECTED BY PUBLIC DOMAIN RESEARCH,"
9150  DATA "AN IMPARTIAL ORGANIZATION DEVOTED TO","THE RESEARCH, EVALUATION,","IMPROVEMENT AND DISSEMINATION OF","PUBLIC DOMAIN WORKS.","*THE PDSOF SERVICE (CONT)","PUBLIC DOMAIN RESEARCH TESTED"
9200  DATA "THOUSANDS OF PROGRAMS.  LESS THAN 10","PER CENT MADE THE GRADE.  AND, MOST","OF THOSE NEEDED WORK."," ","THE PUBLIC DOMAIN RESEARCH STAFF","MADE NUMEROUS ENHANCEMENTS BY","ELIMINATING BUGS AND, AS MUCH AS"
9250  DATA "POSSIBLE, VAGUE INSTRUCTIONS,","CONFUSING ON-SCREEN PROMPTS,","MISLEADING TITLES, SKETCHY","DESCRIPTIONS, POOR GRAMMAR, FAULTY","SYNTAX, IMPROPER USAGE, TYPOS AND","MISSPELLINGS."
9300  DATA "*THE PDSOF SERVICE (CONT)","YOU CAN COPY, MODIFY AND USE ANY OF","THE PROGRAMS FOR YOUR OWN OR A","FRIEND'S PERSONAL USE."," ","BY USING THE PROGRAMS, YOU HONOR THE","AUTHORS."," ","WHEN YOU CUSTOMIZE A PROGRAM, YOU"
9350  DATA "INCREASE ITS VALUE TO YOU.  AS A","BONUS, YOU SHARPEN YOUR PROGRAMMING","SKILLS."," ","JUST REMEMBER, NEVER DELETE A","COPYRIGHT NOTICE OR THE NAMES OF THE","PROGRAM AUTHORS AND ENHANCERS.","*THE PDSOF SERVICE (CONT)"
9400  DATA "WE DEDICATE THE PDSOF COLLECTION TO","THE MANY PEOPLE WHO CREATED THE","PROGRAMS, TO PUBLIC DOMAIN RESEARCH","WHICH ENHANCED THE PROGRAMS, AND TO","YOUR LIBRARY WHICH MAKES THE","PROGRAMS AVAILABLE TO YOU."," "
9450  DATA "FOR MORE INFORMATION ON OUR SERVICE,","READ THE PDSOF USER'S GUIDE BOOKLET.","YOU CAN READ IT AT THE LIBRARIAN'S","DESK.","*"
63111  REM <CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H>          <CTRL-M><CTRL-M>   -------- NOTICE --------<CTRL-M><CTRL-M>        COPYRIGHT 1985<CTRL-M>    PUBLIC DOMAIN RESEARCH<CTRL-M><CTRL-M> ANYONE WISHING TO DISTRIBUTE
63999  REM <CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H> THIS PROGRAM MUST OBTAIN THE<CTRL-M> EXPRESSED WRITTEN CONSENT OF<CTRL-M> THE PUBLISHER.<CTRL-M><CTRL-M>    ----------//----------<CTRL-M><CTRL-M>