0  REM <CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H>        <CTRL-J><CTRL-J>
1  REM <CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H>          -- HELLO --<CTRL-J><CTRL-J>
10 D$ =  CHR$(4)
20  TEXT : HOME : VTAB 10: PRINT  TAB( 14)"WELCOME TO ..."
30  PRINT D$"BLOAD PI.PDSOF"
40  PRINT D$"BLOAD UNPACKER"
50  CALL 768: POKE  -16297,0: POKE  -16304,0: POKE  -16302,0: POKE  -16300,0: POKE 230,32
60  PRINT D$"RUN OPENING MENU"
63111  REM <CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H>          <CTRL-M><CTRL-M>   -------- NOTICE --------<CTRL-M><CTRL-M>        COPYRIGHT 1985<CTRL-M>    PUBLIC DOMAIN RESEARCH<CTRL-M><CTRL-M> ANYONE WISHING TO DISTRIBUTE
63999  REM <CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H> THIS PROGRAM MUST OBTAIN THE<CTRL-M> EXPRESSED WRITTEN CONSENT OF<CTRL-M> THE PUBLISHER.<CTRL-M><CTRL-M>    ----------//----------<CTRL-M><CTRL-M>