0  REM <CTRL-M><CTRL-M><CTRL-M>TIPS FOR BEGINNERS<CTRL-M><CTRL-M>PROGRAM BY GREG TANG<CTRL-M><CTRL-M><CTRL-M>
10  GOTO 70
20  HTAB (21 - LEN(H$)/2): PRINT H$;: RETURN 
30 R = 0:L = 1
40  READ A$: IF A$ = "*"  THEN MX = R: RETURN 
50 B$ =  LEFT$(A$,1): IF B$ < >"*"  THEN A$(R,L) = A$:L = L +1: GOTO 40
60 R = R +1:L = 1:A$(R,0) =  RIGHT$(A$, LEN(A$) -1): GOTO 40
70 D$ =  CHR$(13) + CHR$(4): DIM A$(20,18): HOME : TEXT : INVERSE : VTAB 23: HTAB 2: PRINT " ";: HTAB 39: PRINT " ": HTAB 2: PRINT  TAB( 40);: POKE 34,0: INVERSE : FOR V = 23 TO 2  STEP  -1: VTAB V: HTAB 1: PRINT " ";: HTAB 40: PRINT " ";: NEXT 
80  VTAB 3: HTAB 4: PRINT  TAB( 38);: VTAB 2: HTAB 1: PRINT  TAB( 41);: VTAB 1: HTAB 4: PRINT  TAB( 38): VTAB 2:H$ = "TIPS FOR BEGINNERS": GOSUB 20: NORMAL : VTAB 12:H$ = " ONE MOMENT PLEASE ....": GOSUB 20: POKE  -16368,0: POKE 34,5: GOSUB 40: VTAB 13: HTAB 2: PRINT  TAB( 39);
90  POKE 32,0: POKE 33,40: POKE 34,0: POKE 35,24: FOR I = 1 TO MX: INVERSE : VTAB 2: HTAB 3: PRINT  TAB( 39);:H$ = A$(I,0): GOSUB 20: NORMAL : FOR J = 1 TO 18: VTAB J +4: HTAB 3: PRINT A$(I,J); TAB( 40);: NEXT J: IF I = MX  THEN 110
100  GOSUB 130: NEXT I
110  POKE  -16368,0: VTAB 18: HTAB 18: PRINT "- - -": VTAB 20: HTAB 8: PRINT "PRESS <ESC> TO RETURN TO": HTAB 6: PRINT "THE OPENING MENU OR PRESS ANY": HTAB 4: PRINT "OTHER KEY TO READ THIS FILE AGAIN";: GET A$: IF A$ < > CHR$(27)  THEN 90
120  TEXT : HOME : VTAB 10: HTAB 10: PRINT "LOADING OPENING MENU": VTAB 12: HTAB 13: PRINT "PLEASE WAIT ...": PRINT D$"RUNOPENING MENU"
130  INVERSE : VTAB 24: HTAB 3: PRINT "<ESC> TO EXIT, <ANY KEY> TO CONTINUE";: POKE  -16368,0
140 A =  PEEK( -16384): IF A < = 127  THEN 140
150 A$ =  CHR$(A -128): IF A$ =  CHR$(27)  THEN  NORMAL : GOTO 120
160  VTAB 24: HTAB 2: PRINT  TAB( 40);: NORMAL : RETURN 
9000  DATA "*INTRODUCTION","THIS FILE, 'TIPS FOR BEGINNERS', IS","INTENDED TO SERVE ONLY AS A QUICK-","REFERENCE AID FOR NOVICE USERS.","*INTRODUCTION (CONT)","WE ASSUME THAT YOU HAVE ALREADY","STUDIED"," "
9050  DATA "   - THE APPLE MANUALS WHICH CAME","     WITH YOUR COMPUTER."," ","   - THE 'IMPORTANT: READ ME FIRST'","     FILE ON THIS DISKETTE."," ","IF YOU HAVE NOT YET READ THOSE","DOCUMENTS, AND HAVE NOT YET MADE"
9100  DATA "YOUR COPY OF THE DISKETTE YOU","BORROWED FROM THE LIBRARY, PLEASE DO","SO NOW.","*GETTING STARTED, THE EASY WAY","YOUR COPY WILL BE SELF-BOOTING. THIS","MEANS THAT ALL YOU HAVE TO DO IS","INSERT YOUR COPY IN THE DEFAULT DISK"
9150  DATA "DRIVE, TURN ON THE COMPUTER AND THEN","WAIT FOR THE OPENING MENU TO APPEAR","ON THE SCREEN.","*GETTING STARTED (CONT)","ONCE THE OPENING MENU COMES UP ON","THE SCREEN, YOU CAN GO DIRECTLY TO","THE SELECT-A-PROGRAM MENU SIMPLY BY"
9200  DATA "PRESSING THE NUMBER 5 KEY."," ","ONCE YOU ARE IN THE SELECT-A-PROGRAM","MENU, YOU CAN START THE PROGRAM OF","YOUR CHOICE SIMPLY BY PRESSING THE","LETTER (A TO Z) ASSIGNED TO THAT","PROGRAM.  IT'S THAT EASY."," "
9250  DATA "IF YOU DON'T WANT TO RUN ANOTHER","PROGRAM, REMOVE THE DISK (WHEN THE","DRIVE'S RED LIGHT IS OFF) AND TURN","OFF THE COMPUTER.","*RETURNING TO SELECT-A-PROGRAM MENU","IF YOU WANT TO RUN ANOTHER PROGRAM,"
9300  DATA "FOLLOW THE ON-SCREEN PROMPTS.  THESE","LEAD YOU BACK TO THE SELECT-A-","PROGRAM MENU AUTOMATICALLY."," ","UNFORTUNATELY, WE COULDN'T ADD THIS","FEATURE TO SOME OF THE PROGRAMS IN"
9350  DATA "OUR MULTI-DISKETTE COLLECTION.  WHEN","YOU EXIT THESE PROGRAMS, THE APPLE-","SOFT OR INTEGER PROMPT APPEARS ON","THE SCREEN."," ","THIS ALSO OCCURS IN CERTAIN PROGRAMS","WHEN YOU MAKE AN IMPROPER ENTRY.","*RETURNING (CONT)"
9400  DATA "IN THESE CASES, YOU CAN RETURN TO","THE PROGRAM YOU WERE RUNNING BY","TYPING 'RUN' AND PRESSING THE","<RETURN> KEY."," ","IF THAT DOESN'T WORK, THEN TYPE","'RUN MENU' AND PRESS THE <RETURN>","KEY.  THIS SHOULD RETURN YOU TO"
9450  DATA "THE SELECT-A-PROGRAM MENU.  FROM","THERE, YOU CAN RESELECT THE PROGRAM."," ","IF YOU STILL ENCOUNTER PROBLEMS,","REBOOT THE SYSTEM AND START AGAIN."," ","TO REBOOT, TYPE 'PR#6'.  OR, PRESS","THE 'OPEN APPLE-CONTROL-RESET' KEY"
9500  DATA "COMBINATION.","*RETURNING (CONT)","IF YOU ARE STILL EXPERIENCING","DIFFICULTIES, REINSERT THE DISKETTE","AND GENTLY WIGGLE THE DISK DRIVE","DOOR BEFORE YOU REBOOT THE SYSTEM."," "
9550  DATA "IF ALL THE ABOVE ATTEMPTS FAIL, TURN","OFF THE COMPUTER FOR AT LEAST 15","SECONDS.  THEN, WITH THE DISKETTE IN","THE DRIVE, TURN THE COMPUTER ON."," ","IF SUCCESS STILL ELUDES YOU, REVIEW","THE 'IMPORTANT: READ ME FIRST' FILE"
9600  DATA "ON THIS DISKETTE, RESTUDY YOUR APPLE","MANUALS, OR GET HELP FROM AN","EXPERIENCED USER.","*FOR MORE TIPS","STUDY 'PART ONE -- TIPS FOR","BEGINNERS' IN THE PDSOF USER'S GUIDE"
9650  DATA "BOOKLET.  IT'S AN EXPANDED VERSION","OF THIS FILE AND EXPLAINS HOW TO","VIEW A CATALOG, LIST AND PRINT A","PROGRAM, AND RUN A PROGRAM DIRECTLY","FROM THE APPLESOFT OR INTEGER PROMPT."," "
9700  DATA "YOU CAN READ IT AT THE LIBRARIAN'S","DESK.","*": REM <CTRL-J>
63999  REM <CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H><CTRL-H>  ---====] NOTICE [====---<CTRL-M><CTRL-M>       COPYRIGHT 1985<CTRL-M>   PUBLIC DOMAIN RESEARCH<CTRL-M><CTRL-M>ANYONE WISHING TO DISTRIBUTE<CTRL-M>THIS PROGRAM MUST OBTAIN THE<CTRL-M>EXPRESSED WRITTEN CONSENT OF<CTRL-M>THE PUBLISHER.<CTRL-M><CTRL-M>       ----==][==----